[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "channels>=4.2.2",
    "cryptography>=44.0.2",
    "django>=5.2",
    "uvicorn>=0.34.0",
]
