# Generated by Django 5.2 on 2025-04-09 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='security_code',
            field=models.CharField(blank=True, help_text="Security verification code like WhatsApp's security code", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='security_verified',
            field=models.BooleanField(default=False, help_text='Whether the security code has been verified by the user'),
        ),
        migrations.AddField(
            model_name='message',
            name='ephemeral_key',
            field=models.TextField(blank=True, help_text='Ephemeral key used for this specific message (for perfect forward secrecy)', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_number',
            field=models.PositiveIntegerField(default=0, help_text='Position in the session for key verification'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identity_key_fingerprint',
            field=models.CharField(blank=True, help_text='Fingerprint of identity key for verification', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('root_key', models.TextField(help_text='The current root key for the Double Ratchet Algorithm')),
                ('chain_key', models.TextField(help_text='The current chain key for message encryption')),
                ('next_sending_key', models.TextField(help_text='Key for the next message to be sent')),
                ('message_number', models.PositiveIntegerField(default=0, help_text='Number of messages in this session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_sessions', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'contact')},
            },
        ),
        migrations.AddField(
            model_name='message',
            name='session',
            field=models.ForeignKey(help_text='The session used for encryption', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.conversationsession'),
        ),
        migrations.CreateModel(
            name='OneTimePreKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.PositiveIntegerField(help_text='Identifier for this one-time pre-key')),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_prekeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'key_id')},
            },
        ),
        migrations.CreateModel(
            name='SignedPreKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.PositiveIntegerField(help_text='Identifier for this pre-key')),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
                ('signature', models.TextField(help_text='Signature from identity key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_prekeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'key_id')},
            },
        ),
    ]
