# Generated by Django 5.2 on 2025-04-09 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_security_code_contact_security_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagekey',
            name='private_key',
        ),
    ]
